version: 1
disable_existing_loggers: true

formatters:
  standart:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standart
    stream: ext://sys.stdout
loggers:
  <module>:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: NOTSET
  handlers: [console]
  propagate: yes